CREATE TABLE JENISMKS (
    `ID` INT,
    `NamaMKS` VARCHAR(27) CHARACTER SET utf8
);
INSERT INTO JENISMKS VALUES (2222,' Skripsi');
INSERT INTO JENISMKS VALUES (2223,'Karya Akhir');
INSERT INTO JENISMKS VALUES (2224,'Proposal Tesis');
INSERT INTO JENISMKS VALUES (2225,'Usulan Penelitian');
INSERT INTO JENISMKS VALUES (2226,'Seminar Hasil Penelitian S3');
INSERT INTO JENISMKS VALUES (2227,'Pra Promosi');
INSERT INTO JENISMKS VALUES (2228,'Promosi');
INSERT INTO JENISMKS VALUES (2229,'Tesis');
INSERT INTO JENISMKS VALUES (2230,'Lain - lain');
