CREATE TABLE PRODI (
    `ID` INT,
    `NamaProdi` VARCHAR(28) CHARACTER SET utf8
);
INSERT INTO PRODI VALUES (1111,'S1 Ilmu Komputer');
INSERT INTO PRODI VALUES (1112,'S1 Sistem Informasi');
INSERT INTO PRODI VALUES (1113,'S1 Ilkom Kelas Internasional');
INSERT INTO PRODI VALUES (1114,'S2 MIK');
INSERT INTO PRODI VALUES (1115,'S2 MTI');
INSERT INTO PRODI VALUES (1116,'S3 DIK');
